version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/zip/
    overwrite: yes

# CodeDeploy에서 ec2 서버로 넘겨준 파일들을 모두 ec-user권한 갖도록 함
permissions:
  - object: /home/ec2-user/app/zip/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 700


hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user # ec-user권한으로 deploy.sh를 실행